### ISSUE TITLE
FR: Notetype naming and CSS for tones

### ISSUE THREAD

**Issue by BorisNA** [kerrickstaley/Chinese-Prestudy#25]
1) I propose to change the notetype name (model) from "Chinese" to say "Chinese-Prestudy". There is a high probabilty that the "Chinese" model already exists, so we end with cryptic and ugly models like "Chinese-6613186".

2) Could it be possible to change default CSS code for cards to match Pleco (and add selectors for dark mode)? I can't say that is "defacto standard", but it is quite popular...

```css
.card1 {
  background-color: white;
}

.tone1 {color: red;}
.tone2 {color: green;}
.tone3 {color: blue;}
.tone4 {color: darkmagenta;}
.tone5 {color: gray;}
.night_mode .tone1 {color: red;}
.night_mode .tone2 {color: green;}
.night_mode .tone3 {color: deepskyblue;}
.night_mode .tone4 {color: magenta;}
.night_mode .tone5 {color: gray;}

```
